import Head from "next/head";
import styles from "../styles/Home.module.css";
import Board from "../components/Board";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tic Tac Toe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://preview.redd.it/g8qohwjos2b81.jpg?width=640&crop=smart&auto=webp&s=9c9e199ae5efafca6a620d4fffc6b4568e31480a" />
      </Head>

      <main className={styles.main}>
        <Board />
      </main>
    </div>
  );
}
